var diagnosis = {
    "Apple_Leaf_Scab":{
        "symptoms":"The first visible symptoms of apple scab appear in the spring in the form of minute, circular, olive-green spots on leaves, often along a main vein. As they enlarge, they become brownish-black and eventually coalesce to form large patches of necrotic tissue. Affected leaves are often deformed and fall off prematurely, leading to defoliation in case of heavy infections. On shoots, the infections causes blistering and cracking that can then provide entry for opportunistic pathogens. On the fruits, brown to dark brown circular areas appear on the surface. As they develop further, they often coalesce and become raised, hard and corky. This restricts the expansion of the fruit and leads to distortion and cracking of the skin that expose the flesh. Light attacks do not affect the fruit quality significantly. However, the scabs can expose the fruits to opportunistic pathogens and rots, reducing the storage capacity and the quality.",
        "causes":"Apple scab is a disease caused by the fungus Venturia inaequalis. It survives the winter mainly on infected leaves on the ground but also on bud scales or lesions on wood. At the onset of spring, the fungus resumes growth and starts to produce spores, which are later discharged and dispersed over long distances by the wind. These spores land on developing leaves and fruits and start a new infection. Outer parts of unopened fruit buds are highly susceptible to scab. However, as the fruit matures it becomes much less susceptible. Humid environment, wetting period of leaves or fruits are essential for the infection. Alternative hosts include shrubs of the genus Cotoneaster, Pyracantha and Sorbus. All apple varieties are susceptible to scab, with Gala being more vulnerable.",
        "bioControl":"If disease levels were high the previous season, liquid copper fungicides can be sprayed to impede the fungal growth on the tree during the winter season. Sulfur sprays are only partially effective against apple scab. However, solutions containing sulfur and pyrethrins are available for organic control of the disease during the growing season.",
        "chemControl":"The management of apple scab using chemical controls is primarily concerned with preventing the initiation of primary infection cycles by reducing the germination of ascospores. As such, fungicides are typically applied early in the season, when ascospores are first released. However, fungicide applications may also be made later in the season to prevent infection of old leaves, which can help reduce the amount of primary inoculum for the following season. Benzimidazole fungicides are among the most commonly-used classes of fungicide for managing apple scab in conventional orchards; however, there is some evidence that the disease is developing resistance to this class of fungicides, along with several others, including demethylation inhibitors and quinone outside inhibitors. To manage the development of fungicide resistance, growers can reduce the number of applications made throughout the season and alternate between different classes of fungicide. In organic production systems, growers commonly use copper- or sulfur-based protectant sprays to reduce the efficacy of primary inoculum. Although these sprays were among the earliest methods of preventing the development of apple scab, they do little to manage pre-existing infections and application may significantly damage the foliage of treated trees. Moreover, research has indicated that applications of copper-based fungicides may result in changes in the structure and functionality of soil microbiota, thus having a negative effect on soil health. As such, alternative management strategies appropriate for organic production systems are currently being developed."
    },
    "Apple_Leaf_Black_Rot":{
        "symptoms":"Starting at petal-fall or somewhat later, small, purple specks appear on infected leaves. These specks enlarge to form spots 1/8 to 1/4 inch in diameter. The round to irregularly lobed spots develop a light brown-to-gray center surrounded by one or more dark-brown concentric rings and a purple margin giving it a “frogeye” appearance. Black pycnidia, like those that appear on rotted fruit, may develop on the upper surface in the centers of the older leaf spots. These pycnidia help to distinguish frogeye leaf spots from similar spots caused by spray injury.",
        "causes":"Black rot is caused by the fungus Diplodia seriata (syn Botryosphaeria obtusa). The fungus can infect dead tissue as well as living trunks, branches, leaves and fruits. The black rot fungi survive Minnesota winters in branch cankers and mummified fruit (shriveled and dried fruit) attached to the tree. In wet weather, spores are released from these infections and spread by wind or splashing water. Leaf spots don’t release fungal spores. The fungus infects leaves and fruit through natural openings or minor wounds. Branches and the trunk are most likely to be infected through dead or damaged wood. Leaf spots don’t seriously affect the health of the tree unless many leaves turn yellow and fall off because of the infection (this is rare).",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Apple_Leaf_Cedar_Rust":{
        "symptoms":"Bright yellow/orange spots develop on the upper surface of the leaves in late spring. These spots gradually enlarge, becoming evident on the undersurface of the leaves as small bulges. In midsummer, these rust lesions develop hairlike, cylindrical tubes (hyphae), which release spores into the air that are blown to the juniper host. Infected leaves of apples and crabapples may drop, with defoliation more severe in dry summers. Galls that form on the juniper host do not become evident until July the next year, requiring two years for the fungus to complete its life cycle.",
        "causes":"Cedar-apple rust is the most common of the three fungal rust diseases and attacks susceptible cultivars of apples and crabapples. It infects the leaves, fruit, and, occasionally, young twigs. The alternate host plant, Eastern red cedar (Juniperus virginiana), is necessary for the survival of the fungus. Spores produced on rose family plants only infect juniper plants, and those originating on the evergreen host only infect rose family plants. Repeated infections of cedar-apple rust can be unsightly and seriously weaken and destroy the ornamental value and health of susceptible plants.",
        "bioControl":"Not Available",
        "chemControl":"Protective fungicides can be applied to help minimize infection. A minimum of three applications should be done. These applications protect the new leaves from spores that are dispersed from the juniper host in mid-spring. Spraying apple, crabapple, and hawthorn foliage after symptoms develop has no controlling effect. Apples and Crabapples: Begin spraying when new growth appears and flower buds show color but are not yet open. Repeat three to four times at 10 to 14 day intervals."
    },
    "Apple_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Blueberry_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Cherry_Leaf_Powdery_Mildew":{
        "symptoms":"The infection usually starts off as circular, powdery white spots which can affect leaves, stems and sometimes fruits. It usually covers the upper parts of the leaves but may grow on the undersides as well. The fungus hinders photosynthesis and causes the Leaves turn yellow and dry out and some leaves might twist, break or become disfigured. In the later stages, the buds and growing tips become disfigured.",
        "causes":"Fungal spores overwinter inside leaf buds and other plant debris. Wind, water, and insects transmit the spores to nearby plants. Even though it is a fungus, powdery mildew can develop rather normally in dry conditions. It survives at temperatures between 10-12°C, but optimal conditions are found at 30°C. In contrast to downy mildew, small amounts of rainfall and regular morning dew accelerate the spreading of powdery mildew.",
        "bioControl":"Foliar sprays based on sulfur, neem oil, kaolin or ascorbic acid can prevent severe infection. ",
        "chemControl":"Always consider an integrated approach with preventive measures together with biological treatments if available. In view of the number of crops that are susceptible to powdery mildew, it is difficult to recommend any particular chemical treatment. Fungicides based on wettable sulphur (3 g/l), hexaconazole, myclobutanil (all 2 ml/l) seem to control the growth of the fungus in some crops. "
    },
    "Cherry_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Corn_Cercospora_Leaf_Spot_or_Gray_Leaf_Spot":{
        "symptoms":"Small necrotic (brown or tan) spots that may have a yellow chlorotic halo appear on lower leaves, usually before flowering. Gradually these lesions will turn grayish and appear on younger leaves, too. As the disease progresses, they enlarge into elongated, rectangular lesions that run parallel to the leaf veins. In optimal conditions (warm temperatures, high humidity and wet leaves), they can coalesce and engulf the whole leaf. If this happens before grain filling there can be considerable yield losses. The leaf blight can weaken the plants and sometimes soften the stalks, leading to lodging.",
        "causes":"The gray leaf spot disease is caused by the fungus Cercospora zeae-maydis. It survives in plant residues in the soil for long periods of time. During the spring, the spores are carried onto the lower leaves by rain splashes and wind. Its lifecycle is favored by elevated temperatures (25 to 30°C), high humidity (dews, fogs) and leaf wetness for prolonged periods of time. Hot, dry weather hinders its development. Symptoms vary slightly between different plant varieties. The fungus completes its lifecycle (from infection to production of new spores) in 14-21 days in a susceptible variety and in 21-28 days in a resistant one.",
        "bioControl":"No biological control is available  to control this disease.",
        "chemControl":"Always consider an integrated approach with preventive measures and biological treatments if available. Foliar fungicide treatment is a way to manage the disease if it occurs at early stages but it has to be weighted against the weather conditions, the potential yield loss and the susceptibility of the plant. Fungicides containing pyraclostrobin and strobilurin, or combinations of azoxystrobin and propiconazole, prothioconazole and trifloxystrobin work well to control the fungus."
    },
    "Corn_Leaf_Common_Rust":{
        "symptoms":"Minute flecks appear on both sides of the leaves and slowly develop into small, tan, slightly raised spots. These mainly elongated spots later turn into powdery, golden-brown pustules loosely scattered in patches on upper and lower sides. The color can change to black as the plant matures. Contrarily to other rust diseases, symptoms are not usually present on other plant parts, such as stalks, sheath leaves or husks. However, stalks tend to grow weak and soft and are prone to lodging. Younger leaf tissue is more susceptible to fungal infection than mature leaves. Plants infected during the early stages can show chlorosis of leaves and death, leading to high yield losses if upper leaves are affected.",
        "causes":"The disease is caused by the fungus Puccinia sorghi. The fungus overwinters in an alternate host (a species of Oxalis) and releases spores during the spring. The spores can be transported over great distances by winds and rain. They start the infection process when landing on the leaves. Secondary infection from plant to plant can also occur due to wind and rain. The development of the disease is favored by high relative humidities (nearly 100%), dew, rain and cool temperatures between 15 and 20°C (may vary depending on area). Hot, dry weather will in turn slow or hinder the development of the fungus and the incidence of the disease. It is more a problem in plants used for seed production and sweet corn. Plants cultivated as livestock feed, for industrial products, or to make processed foods are not concerned. Yield is reduced due to lower plant productivity and lodging.",
        "bioControl":"No alternative treatment against Puccinia sorghi is available so far. Please get in touch with us in case you know of anything that might help to fight this disease. Looking forward to hearing from you.",
        "chemControl":"Always consider an integrated approach with preventive measures together with biological treatments if available. The application of fungicides can be beneficial when used on susceptible varieties. Apply a foliar fungicide early in the season if rust is bound to spread rapidly due to the weather conditions. Numerous fungicides are available for rust control. Products containing mancozeb, pyraclostrobin, pyraclostrobin + metconazole, pyraclostrobin + fluxapyroxad, azoxystrobin + propiconazole, trifloxystrobin + prothioconazole can be used to control the disease. An example of treatment could be: Spraying of mancozeb @ 2.5 g/l as soon as pustules appear and repeat at 10 days interval till flowering."
    },
    "Corn_Northern_Leaf_Blight":{
        "symptoms":"The symptoms appear as small, oval, water-soaked spots on the lower leaves first. As the disease progresses, they start to appear on the upper part of the plant. Older spots slowly grow into tan, long cigar-shaped necrotic lesions with distinct dark specks and pale green, water-soaked borders. These lesions later coalesce and engulf a large part of the leaf blade and stalk, sometimes leading to death and lodging. If the infection spreads to the upper parts of the plant during the development of the cob. Severe yield losses can occur (up to 70%).",
        "causes":"The fungus overwinters in the soil or on plant debris.  Rainfall, night dew, high humidity and moderate temperatures favor the dispersion of the the fungus. Carried by wind or rain splashes it first spreads from the soil onto the lower leaves of young maize plants. Rainy conditions and poor field practices favor its spread to other plants and within fields. Optimal temperatures for infection are in the range of 18 to 27°C during the growing season. A prolonged period of 6 to 18 hours of leaf wetness are also necessary. Sorghum is another favorite host of the fungus.",
        "bioControl":"Bio-fungicides based on Trichoderma harzianum, or Bacillus subtilis can be applied at different stages to decrease the risk of infection. Application of sulfur solutions is also effective.",
        "chemControl":"Fungicides are available to help manage northern corn leaf blight. These fungicides will help to minimize yield loss; however, keep in mind other economic factors when determining how valuable this management method would be. The most important area to prevent infection from reaching is the ear leaves and above, which is another factor to consider when deciding whether or not a fungicide is necessary. In this case, scout corn fields right before tassel emergence. If infection is already bad, this is the period in which the fungus can be controlled most effectively. Fungicides with the following active ingredients have proven to be effective for the management of northern corn leaf blight: picoxystrobin (Aproach®), tetraconazole (Domark®), pyraclostrobin (Headline® AMP), azoxystrobin (Quadris®), and propiconazole (Tilt®). Always be sure to carefully read the label for cautions and proper application before use."
    },
    "Corn_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Grape_Leaf_Black_Rot":{
        "symptoms":"Irregular spots appear on the leaves, which are framed by a dark line. Shoots, stems and leaf stalks can also show symptoms of these spots. If leaf stalks are affected the whole leaves will dry. Grapes will show grey discolorations in the first beginning, which then turn to reddish-brown or violet spots. The fruit will become deformed and eventually be shriveled and black mummified.",
        "causes":"The damage is caused by the fungus Phyllosticta ampelicida. The pathogen overwinters in infested shoots or fruit mummies on the grapevine or the soil. The spores will be ejected by light rainfall and then dispersed via wind. Optimal growth conditions are met at 25°C and 6 hours of constant leaf wetness. The fungus prefers warm and humid weather. Reduced fruit yield.",
        "bioControl":"Immediately after blooming stage you can spray Bacillus thuringiensis.",
        "chemControl":"Chemical applications are done in a preventive manner. Start spraying roughly two weeks before bloom with captan + mycobutanil or mancozeb + mycobutanil. Just before the blossoms open you can also use carbaryl or imidcloprid. Post-bloom spray mancozeb + mycobutanil, imidacloprid or azadirachtin. Ten days after bloom you can also apply a mixture of captan and sulfur on your vines. Because most grape varieties become resistant to the infection three to four weeks after bloom, chemical sprays should be avoided at that time."
    },
    "Grape_Leaf_Esca_Black_Measles":{
        "symptoms":"The disease may occur at any time during the growing season. The main symptom is an interveinal 'striping' on the leaves, which is characterized by the discoloration and drying of the tissues around the main veins. It usually shows as dark red in red varieties and yellow in white ones. Leaves can dry out completely and drop prematurely. On berries, small, round, dark spots, often bordered by a brown-purple ring, may occur. These fruit spots may appear at any time between fruit set and ripening. In severely affected vines, the berries often crack and dry. Cross-sectional cuts through affected canes, spurs, cordons, or trunks reveal concentric rings formed by dark spots. A severe form of Esca known as 'apoplexy' results in a sudden dieback of the entire vine.",
        "causes":"The symptoms are mainly caused by the fungus Togninia minima but other fungi can also be involved (for example Phaeomoniella chlamydospora). The infection actually occurs in younger vines but the symptoms may first become apparent in vineyards after 5-7 years.  The fungi survive the winter in overwintering structures embedded in the woody parts of the vines. During fall to spring rainfall, spores are produced and released and may infect wounds done during dormant pruning. Wounds may remain susceptible to infection for several weeks after pruning. After a pruning wound is infected, the pathogen establishes a permanent, localized wood infection, which cannot be eradicated by fungicide applications.",
        "bioControl":"Soak dormant cuttings for 30 mins in hot water at about 50°C. This treatment is not always effective and must therefore be combined with other methods. Some species of Trichoderma have been used to prevent the infection of pruning wounds, basal ends of propagation material, and graft unions. This treatment has to be carried out within 24 hours of pruning and again 2 weeks after.",
        "chemControl":"Always consider an integrated approach with preventive measures together with biological treatments if available. Chemical strategies to control this disease are difficult, since the traditional wound protectants do not penetrate deep enough in the dormant grapevine cuttings to affect the fungi. Preventive practices are the most effective management approach for all trunk diseases. For example, immediately before grafting, vines can be deeped into specialized waxes containing plant growth regulators or fungicide-impregnated formulations. This encourages graft union callus development while inhibiting fungal contamination."
    },
    "Grape_Leaf_Blight_or_Isariopsis_Leaf_Spot":{
        "symptoms":"On leaf surface we will see lesions which are irregularly shaped (2 to 25 mm in diameter). Initially lesions are dull red to brown in color turn black later. If disease is severe this lesions may coalesce. On berries we can see symptom similar to black rot but the entire clusters will collapse.",
        "causes":"Fungus",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Grape_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Orange_Leaf_Haunglongbing_(Citrus_Greening)":{
        "symptoms":"First symptom is usually the appearance of a yellow shoot on the tree, thereby one of the common name of the disease, huanglongbing (yellow dragon disease). Leaves progressively turn pale-yellow and display a diffuse blotchy mottling that may resemble zinc or manganese deficiency. A common way to tell these disorders apart is that the symptoms of these deficiencies tend to be symmetrical along the leaf vein, while those of the disease are asymmetrical. Chronically infected trees show stunted growth, premature defoliation and twig dieback. Trees may bear multiple off-season flowers that later fall off and small, irregular fruits with a thick, pale peel that remains green at the bottom.",
        "causes":"The symptoms of huanglongbing (HLB) are caused by the bacterium Candidatus Liberibacter asiaticus. It is transmitted persistently by two psyllid vectors that are omnipresent in the citrus grooves, Diaphorina citri and Trioza erytreae. HLB can be acquired by both nymphs and adults, which can maintain and transmit the disease throughout their 3- to 4-month lifespan. Huanglongbing is systemic and has an incubation period of three months to several years before symptoms are visible. The disease can also be spread through grafting, even though with variable transmission rates. Seed transmission may also be possible. Other pathologies or disorders also show such a mottling of the leaves. It is thus recommended to send samples of tissues for analysis in laboratories to ascertain the cause.",
        "bioControl":"Not Available",
        "chemControl":" Always consider an integrated approach with preventive measures and biological treatments if available. An appropriate use of insecticides has resulted in good control of the psyllid vectors and thus a limited spread of the disease. Injection of the antibiotic tetracycline into the trunk of the trees may result in a partial recovery but has to be repeated often to show effect. Tetracycline is phytotoxic and may have adverse effects on the environment. For these reasons, its use has decreased in recent years. "
    },
    "Peach_Leaf_Bacterial_Spot":{
        "symptoms":"Symptoms vary widely depending on the species of tree affected. Initially, small, water-soaked and grayish spots appear on the lower leaf side, most commonly near the tip or along the midrib. Over time, they become angular to irregular and purple, brown or black. Sometimes their centers become necrotic and fall out, leaving ragged shot-hole. Severely infected leaves become chlorotic or scorched and may drop early, causing defoliation. Small, round, sunken spots form on the fruit, sometimes only on the side exposed to the sun. They are olive-brown to black and frequently surrounded by a water-soaked margin. As the fruit matures, they harden and in some cases, exude a yellowish gum after rainy periods. Opportunistic pathogens may colonize cracked or damaged fruit and cause them to rot. Pustules appear on twigs and later develop into cankers that release bacterial ooze.",
        "causes":"The symptoms are caused by the bacterium Xanthomonas arboricola, whose common hosts are peach, nectarine, prune, plum, and apricot. It overwinters on buds, cracks of the stem or in leaf scars. In spring, when conditions are favorable, it resumes its growth and colonize the rest of the twigs, exuding bacterial ooze as it does so. The ooze is dispersed by dropping dew, wind or splashing rain and carried to healthy twigs, fruits and leaves. The natural pores on leaves or the lenticels on bark are the entry points for the bacteria. Warm temperatures (21 to 29 °C) with light rains, heavy dews, and windy weather are most conducive for disease development and spread. By contrast, the growth of the bacterium and the infection process is impaired when the weather is hot and dry. The disease leads to yield losses, which can be very high in some particularly susceptible varieties.",
        "bioControl":"Not Available",
        "chemControl":" Always consider an integrated approach with preventive measures together with biological treatments, if available. There are no completely successful spray programs for the control of bacterial spot. A combination of preventive measures and chemical treatments are necessary to reduce its incidence. Copper-based sprays alone or together with an antibiotic can be used preventively with moderate efficacy. Dosage must be reduced progressively to avoid damage to leaves."
    },
    "Peach_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Pepper_Bell_Leaf_Bacterial_Spot":{
        "symptoms":"The first symptoms are small, yellow-green lesions on young leaves, which usually appear deformed and twisted. On older foliage, lesions are rather angular, dark-green, and greasy in appearance, often surrounded by yellow circles. They are often more numerous on leaf margins or tips. Eventually, the spots look like shot holes because the center dries up and disintegrates. Fruit spots (up to 0.5 cm) start off as pale-green, water-soaked areas, which eventually roughen, becoming brown and scabbed.",
        "causes":"Bacterial spot occurs worldwide and is one of the most devastating diseases on pepper and tomato crops grown in warm, moist environments.  The pathogen can survive in association with seeds, either externally or internally as well as on specific weeds and later spreads through rain or overhead irrigation. It enters the plant through leaf pores and wounds. Optimum temperatures range from 25 to 30°C. Once the crop is infected, the disease is very difficult to control and can lead to total crop losses.",
        "bioControl":"Bacterial Spot is very difficult and expensive to treat. If the disease occurs early in the season, consider destroying the entire crop. Copper-containing bactericides provide a protective cover on foliage and fruit. Bacterial viruses (bacteriophages) that specifically kill the bacteria are available.  Submerge seeds for one minute in 1.3% sodium hypochlorite or in hot water (50°C) for 25 minutes. ",
        "chemControl":"Always consider an integrated approach with preventive measures together with biological treatments if available. Copper-containing bactericides can be used as a protectant and give partial disease control. Application at the first sign of disease and then at 10- to 14-day intervals when warm, moist conditions prevail. The active ingredients copper and mancozeb give a better protection. "
    },
    "Pepper_Bell_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Potato_Leaf_Early_Blight":{
        "symptoms":"Symptoms of early blight occur on older foliage, stem, and fruits. Gray to brown spots appear on leaves and gradually grow in a concentric manner around a clear center - the characteristic “bullseye” formation. These lesions are surrounded by a bright yellow halo. As the disease progresses, entire leaves may turn chlorotic and shed, leading to significant defoliation. When leaves die and fall, fruits become more vulnerable to sun scald. The same type of spots with a clear center appears on stems and fruits. The fruits begin to rot and may eventually fall off.",
        "causes":"Symptoms are caused by Alternaria solani, a fungus that overwinters on infected crop debris in soil or on alternative hosts. Purchased seeds or seedlings may also be already contaminated. Lower leaves often get infected when in contact with contaminated soil. Warm temperatures (24-29°C) and high humidity (90%) favor development of the disease. A long wet period (or alternating wet/dry weather) enhances the production of spores, which may be spread via wind, splashing rain or overhead irrigation. Tubers harvested green or in wet conditions are particularly susceptible to an infection. It often strikes after a period of heavy rainfall and is particularly destructive in tropical and subtropical areas.",
        "bioControl":"Application of products based on Bacillus subtilis or copper-based fungicides registered as organic can treat this disease.",
        "chemControl":"Fungicides are necessary for effective early blight management in most potato production regions. The first spray should be applied when airborne spores appear, which coincides with the first appearance of lesions. Fungicides applied before the first lesion appearance do not contribute to disease suppression and are not necessary. Several disease forecasting systems have been developed and validated in the High Plains region, and can significantly reduce the number of fungicide applications necessary for effective early blight control. Fungicide chemistries should be rotated or tank-mixed to delay resistance development in the fungus. Copper-based fungicides are not highly effective against early blight. Resistance to strobilurin fungicides such as azoxystrobin (Quadris) have been document in several potato production regions in the U.S., and these fungicides may provide little or no control if resistant strains of the pathogen exist."
    },
    "Potato_Leaf_Late_Blight":{
        "symptoms":"Dark brown spots develop on the leaves starting at the tip or the leaf margins. In humid climates, these spots become water-soaked lesions. A white fungal covering can be seen on the underside of the leaves. As the disease progresses, entire leaves become necrotic, turn brown and die off. Similar lesions develop on stems and petioles. The potato tubers have greyish-blue spots on their skin and their flesh also turns brown, making them inedible. The rotting of the infested fields emits a distinctive odor.",
        "causes":"This fungus is an obligate parasite. This means that it must overwinter in plant debris and tubers as well as on alternative hosts to survive. It enters the plant via wounds and rips in the skin. Fungal spores germinate at higher temperatures during the spring and spread through wind or water. The disease is more severe in periods of cool nights (below 18°C), warm days (18-22°C), and extended wet conditions such as rain and fog (90% relative humidity). In these conditions, a late blight epidemic can occur.",
        "bioControl":"Apply copper-based fungicides before dry weather. Foliar sprays of organic coating agents can also prevent the infection.",
        "chemControl":"Fungicides are essential to suppressing potato late blight when disease occurs. Seed treated mancozeb-containing fungicides can reduce the contamination of healthy seed pieces during cutting and handling. Protectant fungicides should be applied prior to infection. Disease forecasting systems have been developed that can improve scouting and fungicide timing in the High Plains, and should be used, if available, to reduce unnecessary sprays. Fungicides banded over seedlings at emergence can reduce secondary spread of disease early in the growing season, if forecasts call for treatments to be applied. Strains of the pathogen resistant to metalaxyl are found in many areas of the High Plains. Fungicides with a different mode of action should be used where resistant strains are common."
    },
    "Potato_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Raspberry_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Soybean_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Squash_Leaf_Powdery_Mildew":{
        "symptoms":"The infection usually starts off as circular, powdery white spots which can affect leaves, stems and sometimes fruits. It usually covers the upper parts of the leaves but may grow on the undersides as well. The fungus hinders photosynthesis and causes the Leaves turn yellow and dry out and some leaves might twist, break or become disfigured. In the later stages, the buds and growing tips become disfigured.",
        "causes":"Fungal spores overwinter inside leaf buds and other plant debris. Wind, water, and insects transmit the spores to nearby plants. Even though it is a fungus, powdery mildew can develop rather normally in dry conditions. It survives at temperatures between 10-12°C, but optimal conditions are found at 30°C. In contrast to downy mildew, small amounts of rainfall and regular morning dew accelerate the spreading of powdery mildew.",
        "bioControl":"Foliar sprays based on sulfur, neem oil, kaolin or ascorbic acid can prevent severe infection. ",
        "chemControl":" Always consider an integrated approach with preventive measures together with biological treatments if available. In view of the number of crops that are susceptible to powdery mildew, it is difficult to recommend any particular chemical treatment. Fungicides based on wettable sulphur (3 g/l), hexaconazole, myclobutanil (all 2 ml/l) seem to control the growth of the fungus in some crops. "
    },
    "Strawberry_Leaf_Scorch":{
        "symptoms":"Small, dark purple spots develop on upper leaf surfaces and remain dark purple. A white center never forms, as with common leaf spot. Spots have an irregular outline. If numerous, spots run together, and leaves appear scorched. In severe cases, foliage is reduced considerably, and plants may be stunted. Infected fruit has elongated, slightly sunken, reddish areas or streaks, but the marks disappear as the fruit ripens.",
        "causes":"Diplocarpon fragarie, a fungus that overwinters on old infected leaves. The disease is frequent in northern Idaho and western Oregon and Washington. Conidia are produced in acervuli and are splashed to healthy tissue. Conidia are sticky and can directly penetrate the leaf cuticle. In spring rains, spores from just a few diseased plants can multiply and spread through the entire planting. Generally more severe in second- and third-year fields.",
        "bioControl":"Serenade ASO (Bacillus subtilis strain QST 713) at 2 to 4 quarts/A. Active ingredient is a small protein. 4-hr reentry.",
        "chemControl":"Copper-Count-N at 1.5 to 2 quart/100 gal water. Group M1 fungicide. 48-hr reentry. Monterey Liqui-Cop at 1 to 2 teaspoons/gal water. Topsin 4.5 FL at 15 to 20 fl oz/A plus another fungicide. Do not apply within 1 day of harvest. Group 1 fungicide. 24-hr reentry."
    },
    "Strawberry_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    },
    "Tomato_Leaf_Bacterial_Spot":{
        "symptoms":"Symptoms can be seen on the foliage, stems, and fruits of tomatoes. Initially small yellow-green lesions appear on young leaves for bacterial spot, whilst bacterial speck causes black spots with a narrow yellow halo. They are usually more numerous on leaf margins or tips, which may appear deformed and twisted. In severe cases, the spots of bacterial speck may coalesce or overlap, resulting in larger and irregular lesions. Bacterial spot lesions can enlarge from 0.25 cm to 0.5 cm and become tan to brownish-red, which will eventually look like shot holes when the center dries up. Bacterial spot produces similar lesion of fruits as it does on the leaves and eventually roughen, becoming brown and scabbed. Bacterial speck causes tiny, slightly raised black specks. It is difficult to distinguish between these two diseases at an early stage.",
        "causes":"Bacterial Spot and Speck are caused by several species of bacteria of the genus Xanthomonas, and Pseudomonas syringae pv. tomato. Bacterial spot occurs worldwide and is one of the most devastating diseases on tomatoes grown in warm, moist environments. The pathogens can survive in or on seeds, plant debris, and specific weeds. Xanthomonas has a limited survival period of days to weeks in the soil. Secondary infection can occur through rain or overhead irrigation. It enters the plant tissues through leaf pores and wounds. Optimal temperatures range from 25 to 30°C for the bacterial spot. Once the crop is infected, the disease is very difficult to control and can lead to total crop losses. Bacterial speck outbreaks are relatively infrequent and are favored by prolonged leaf moisture and cool temperatures.",
        "bioControl":"Bacterial Spot is very difficult to control and also expensive to treat. If the disease occurs early in the season, consider destroying the entire crop. Copper-containing bactericides provide a protective cover on foliage and fruit for both bacteria. Bacterial viruses (bacteriophages) that specifically kill the bacteria are available for the bacterial spot. Submerging seeds for one minute in 1.3% sodium hypochlorite or in hot water (50°C) for 25 minutes can reduce the incidence of both diseases.",
        "chemControl":"Not Available"
    },
    "Tomato_Leaf_Early_Blight":{
        "symptoms":"Symptoms of early blight occur on older foliage, stem, and fruits. Gray to brown spots appear on leaves and gradually grow in a concentric manner around a clear center - the characteristic “bullseye” formation. These lesions are surrounded by a bright yellow halo. As the disease progresses, entire leaves may turn chlorotic and shed, leading to significant defoliation. When leaves die and fall, fruits become more vulnerable to sun scald. The same type of spots with a clear center appears on stems and fruits. The fruits begin to rot and may eventually fall off.",
        "causes":"Symptoms are caused by Alternaria solani, a fungus that overwinters on infected crop debris in soil or on alternative hosts. Purchased seeds or seedlings may also be already contaminated. Lower leaves often get infected when in contact with contaminated soil. Warm temperatures (24-29°C) and high humidity (90%) favor development of the disease. A long wet period (or alternating wet/dry weather) enhances the production of spores, which may be spread via wind, splashing rain or overhead irrigation. Tubers harvested green or in wet conditions are particularly susceptible to an infection. It often strikes after a period of heavy rainfall and is particularly destructive in tropical and subtropical areas.",
        "bioControl":"Application of products based on Bacillus subtilis or copper-based fungicides registered as organic can treat this disease.",
        "chemControl":"Use protectant fungicides, mancozeb, chlorothalonil or copper products. Systemic products are available, e.g., strobilurins, although they are expensive and, if used too often, the fungus may develop resistance to them."
    },
    "Tomato_Leaf_Late_Blight":{
        "symptoms":"Brownish-green spots appear on the leaf margins and leaf tops. Later, large areas of the leaves turn brown completely. During wet weather, lesions on the lower side of the leaves may be covered with a gray to white moldy growth, making it easier to distinguish healthy from dead leaf tissue. As the disease progresses, the foliage runs brown, curls and dries. In some cases, the sharply delimited brown spots and the white covering also appear on the stems, branches, and petioles. Greyish-green to dirty-brown and wrinkled stains appear on the fruits. At these spots, the fruit flesh is hardened.",
        "causes":"The risk of infection is highest in midsummer. The fungus enters the plant via wounds and rips in the skin. Temperature and moisture are the most important environmental factors affecting the development of the disease. Late blight fungi grow best in high relative humidities (around 90%) and in temperature ranges of 18 to 26°C. Warm and dry summer weather can bring the spread of the disease to a halt.",
        "bioControl":"At this point, there is no biological control of known efficacy against late blight. To avoid spreading, remove and destroy plants around the infected spot immediately and do not compost infected plant material.",
        "chemControl":" Always consider an integrated approach with preventive measures together with biological treatments if available. Use fungicide sprays based on mandipropamid, chlorothalonil, fluazinam, mancozeb to combat late blight. Fungicides are generally needed only if the disease appears during a time of year when rain is likely or overhead irrigation is practiced."
    },
    "Tomato_Leaf_Mold":{
        "symptoms":"Symptoms commonly occur on both sides of the foliage and sometimes on fruit. Older leaves are infected first and then the disease slowly moves up towards young leaves. On the upper leaf surface, small, diffuse, pale green or yellowish spots with indefinite margins appear. On the underside, olive green to grayish purple and velvety patches develop below the leaf spots. These are composed of spore-producing structures and spore masses (conidia). Over time, as the spots enlarge, the color of the infected leaf changes from yellowish (chlorosis) to brown (necrosis) and the leaf begins to curl and dry. The leaves will drop prematurely, leading to defoliation in severe cases. Occasionally, this pathogen causes disease on the blossoms or fruits with various symptoms. The blossoms may turn black and will be killed before fruit set. Green and ripe fruits will develop smooth black irregular area on the stem end. As the disease progresses, the infected area becomes sunken, dry and leathery.",
        "causes":"The symptoms are caused by the fungus Mycovellosiella fulva, whose spores can survive without a host for 6 months to a year at room temperature (non-obligate). Prolonged leaf moisture and humidities above 85% favor the germination of spores. The temperature must be between 4° to 34 °C for spores to germinate, with an optimum temperature at 24-26°C. Dry conditions and the absence of free water on leaves impair germination. The symptoms usually start to appear 10 days after inoculation with the development of spots on both sides of the leaf blade. On the underside, a large number of spore-producing structures are formed and these spores are easily spread from plant to plant by the wind and water splashing, but also on tools, clothing of workers and insects. The pathogen usually infects the leaves by penetrating through stomata in a high humidity level.",
        "bioControl":"Seed treatment with hot water (25 minutes at 122 °F or 50 °C) is recommended to avoid the pathogen on seeds. The fungi Acremonium strictum, Dicyma pulvinata, Trichoderma harzianum or T. viride and Trichothecium roseum are antagonistic to M. fulva and could be used to reduce its spread. In greenhouse trials the growth of M. fulva on tomatoes was inhibited by A. strictum, Trichoderma viride strain 3 and T. roseum by 53, 66 and 84% respectively. In small arms, apple-cider, garlic or milk sprays and vinegar mix can be used to treat the mold.",
        "chemControl":"Always consider an integrated approach with preventive measures together with biological treatments if available. Applications should be made prior to infection when environmental conditions are optimal for the development of the disease. Recommended compounds in field use are chlorothalonil, maneb, mancozeb and copper formulations. For greenhouses, difenoconazole, mandipropamid, cymoxanil, famoxadone and cyprodinil are recommended."
    },
    "Tomato_Septoria_Leaf_Spot":{
        "symptoms":"Symptoms spread upwards from oldest to youngest growth. Small, water-soaked grey circular spots with dark-brown margins appear on the undersides of older leaves. At later stages of the disease, the spots enlarge and coalesce, and black dots appear in their centers. The same pattern may also be observed on stems and blossoms, but rarely on fruit. Heavily infected leaves will turn slightly yellow, wither, and fall off. The defoliation leads to sun scalding of fruit.",
        "causes":"Septoria leaf spot occurs worldwide and is caused by the fungus Septoria lycopersici. The fungus infects only plants of the family of potato and tomato. The temperature range for the development of the fungus varies between 15° and 27°C, with optimal growth at 25°C. Spores might be spread by overhead water, splashing rain, hands and clothing of pickers, insects such as beetles, and cultivation equipment. It overwinters on solanaceous weeds and for short periods in soils or soil debris.",
        "bioControl":"Copper-based fungicides, such as Bordeaux mixture, copper hydroxide, copper sulfate, or copper oxychloride sulfate might help control the pathogen. Apply at 7 to 10 day intervals throughout the late season. Follow harvest restrictions listed on the pesticide label.",
        "chemControl":" Always consider an integrated approach with preventive measures together with biological treatments if available. Fungicides containing maneb, mancozeb, chlorothalonil effectively control Septoria leaf spot. Apply at 7 to 10 day intervals throughout the season, mainly during flowering and fruit setting. Follow harvest restrictions listed on the pesticide label."
    },
    "Tomato_Leaf_Spider_Mites_(Two_Spotted_Spider_Mite)":{
        "symptoms":"The spider mites feeding causes white to yellow speckles to form on the upper surface of the leaves. As infestation becomes more severe, leaves appear bronzed or silvery first and then become brittle, rip open between the leaf veins, and finally fall off. Spider mite eggs can be found on undersides of leaves. The spider mite itself is located there, nesting in a cocoon resembling webbing. Infected plants will be covered by a web spun by the spider mites. Shoot tips can become bald and as  a result, side shoots start to grow. In cases of heavy damage, the quantity, as well as quality of fruits, is reduced.",
        "causes":"Damage is caused by spider mites from the genus Tetranychus, mainly T. urticae and T. cinnabarinus. The adult female is 0.6 mm long, pale green with two darker patches on its oval body, and long hairs on the back. Overwintering females are reddish. In spring, the females lay globular and translucent eggs on the underside of the leaves. The nymphs are pale green with darker markings on the dorsal side. The mites protect themselves with a cocoon on the underside of the leaf blades. The spider mite thrives in dry and hot climates and will produce up to 7 generations in one year in these conditions. There is a wide range of alternative hosts, including weeds.",
        "bioControl":"In case of minor infestation, simply wash off the mites and remove the affected leaves. Use preparations based on rapeseed, basil, soybean and neem oils to spray leaves  thoroughly and reduce populations of T. urticae.  Also try garlic tea, nettle slurry or insecticidal soap solutions to control the population. In fields, employ host-specific biological control with predatory mites (for example Phytoseiulus persimilis) or the biological pesticide Bacillus thuringiensis. A second spray treatment application 2 to 3 days after the initial treatment is necessary.",
        "chemControl":" Always consider an integrated approach with preventive measures together with biological treatments if available. Spider mites are very difficult to control with acaricides because most populations develop resistance to different chemicals after a few years of use. Choose chemical control agents carefully so that they do not disrupt the population of predators. Fungicides based on wettable sulfur (3 g/l), spiromesifen (1 ml/l), dicofol (5 ml/l) or abamectin can be used for example (dilution in water). A second spray treatment application 2 to 3 days after the initial treatment is necessary."
    },
    "Tomato_Leaf_Target_Spot":{
        "symptoms":"The disease starts on the older leaves and spreads upwards. The first signs are irregular-shaped spots (less than 1 mm) with a yellow margin. Some of the spots enlarge up to 10 mm and show characteristics rings, hence the name of target spot. Spread to all leaflets and to other leaves is rapid, causing the leaves to turn yellow, collapse and die. Spots also occur on the stems. They are long and thin. Small light brown spots with dark margins may also occur on the fruit. The spores are spread by wind-blown rain, and if windy wet weather continues for a few days, spread is fast and plants lose their leaves quickly.",
        "causes":"The fungus causes plants to lose their leaves; it is a major disease. If infection occurs before the fruit has developed, yields are low. This is a common disease on tomato in Pacific island countries. The disease occurs in the screen house and in the field.        ",
        "bioControl":"Not Available",
        "chemControl":"Warm wet conditions favour the disease such that fungicides are needed to give adequate control. The products to use are chlorothalonil, copper oxychloride or mancozeb. Treatment should start when the first spots are seen and continue at 10-14-day intervals until 3-4 weeks before last harvest. It is important to spray both sides of the leaves."
    },
    "Tomato_Yellow_Leaf_Curl_Virus":{
        "symptoms":"Infection at seedling stage results in  severe stunting of young leaves and shoots, leading to a somewhat bushy growth of the plant. In older plants, the infection results in excessive branching, thicker and wrinkled leaves, and interveinal chlorosis clearly visible on the leaf blade. At later stages of the disease, the plants take a leathery texture and their chlorotic margins are rolled upwards and inwards. If the infection takes place before the flowering stage, the number of fruits is considerably reduced, even though there are no noticeable symptoms on their surface.",
        "causes":"TYLCV is not seed-borne and is not transmitted mechanically. It is spread by whiteflies of the Bemisia tabaci species. These whiteflies feed on the lower leaf surface of a number of plants and are attracted by young tender plants. The whole infection cycle can take place in about 24 hours and is favored by dry weather with high temperatures.",
        "bioControl":"There is no treatment against TYLCV. Control the whitefly population to avoid the infection with the virus.",
        "chemControl":"Once infected with the virus, there are no treatments against the infection. Control the whitefly population to avoid the infection with the virus. Insecticides of the family of the pyrethroids used as soil drenches or spray during the seedling stage can reduce the population of whiteflies. However, their extensive use might promote resistance development in whitefly populations. "
    },
    "Tomato_Leaf_Mosaic_Virus":{
        "symptoms":"All plant parts can be affected during any growth stage. The symptoms depend on environmental conditions (light, day length, temperature). Infected leaves show a green and yellow mottling or a mosaic pattern. Younger leaves are slightly distorted. Older leaves show raised dark green areas. In some cases, dark necrotic streaks appear in stems and petioles. Plants are stunted to varying degrees and fruit set may be severely reduced. Unevenly ripening fruits develop brown spots on their surface, and internal, browning blotches in the fruit wall. Crop yield might be reduced significantly.",
        "causes":"The virus can persist in plant or root debris in dry soil for periods of over 2 years (1 month in most soils). Plants get contaminated through minor wounds in roots. The virus can spread via infested seeds, seedlings, weeds, and contaminated plant parts. Wind, rain, grasshoppers, small mammals, and birds can also transport the virus between fields. Bad cultural practices during plant handling favor virus transmission, too. Day length, temperature, and light intensity, as well as plant variety and age, determine the severity of the infection.",
        "bioControl":" Dry heating seeds at 70°C for 4 days or at 82-85°C for 24 hours will help to rid them of the virus. Alternatively, seeds can be soaked for 15 min in a solution of 100 g/l of trisodium phosphate, rinsed thoroughly with water and dried. ",
        "chemControl":" Always consider an integrated approach with preventive measures together with biological treatments if available. There is no effective chemical treatment against Tomato Mosaic Virus."
    },
    "Tomato_Healthy_Leaf":{
        "symptoms":"Not Available",
        "causes":"Not Available",
        "bioControl":"Not Available",
        "chemControl":"Not Available"
    }
};

module.exports = diagnosis;